[package]
name = "vita"
version = "0.1.0"
authors = ["Junn <likesgophers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.0.0-alpha.4"
url = "2.1.1"
lazy_static = "1.4.0"
futures = "0.3.5"
serde = "1.0.113"
serde_json = "1.0.55"
http-types = "2.2.1"
dotenv = "0.15.0"
futures-await-test = "0.3.0"

[dependencies.async-std]
version = "1.6.2"
features = ["attributes"]
